dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    // jei from maven central
    api("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // Jade maven central
    implementation "maven.modrinth:jade:${jade_version}"

    // kubejs
    implementation("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    // rhino
    implementation "dev.latvian.mods:rhino:${rhino_version}"

    // ae2 from maven central
    runtimeOnly "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    implementation "org.appliedenergistics:appliedenergistics2:${ae2_version}:api"
    compileOnly "org.appliedenergistics:appliedenergistics2:${ae2_version}"
    // guide me from maven central
    implementation "org.appliedenergistics:guideme:${guideme_version}"

    // mekanism from howxu maven, recently it's unusable
    runtimeOnly "mekanism:Mekanism:${mekanism_version}"
    implementation "mekanism:Mekanism:${mekanism_version}:api"
    compileOnly "mekanism:Mekanism:${mekanism_version}"

    // ExtendedAE 26.1-1.0.3-neoforge
    implementation "maven.modrinth:${eae_id}:${eae_version}"
    // glodium 26.1-1.2-neoforge
    implementation "maven.modrinth:${glodium_id}:${glodium_version}"

    // AppliedFlux 26.1-1.0.1-neoforge
    implementation "curse.maven:${aeflux_id}:${aeflux_version}"

    // athena 4.7.3
    compileOnly "curse.maven:${athena_id}:${athena_version}"
    // here's some test need, cause this is a pure client mod
    localRuntime "curse.maven:${athena_id}:${athena_version}"

    // junit
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.25.0'

    // 1.21.1 only for test and runtime
    implementation("de.mari_023:${ae2wtlib_id}:${ae2wtlib_version}")
}

dependencies {
    gametestCompileOnly fileTree("${gradle.gradleUserHomeDir}/caches/neoformruntime/intermediate_results") {
        include 'compiledWithNeoForge_*_output.jar'
    }
}
