tasks.register('apiJar', Jar) {
    archiveClassifier = 'api'
    from sourceSets.main.output
    from sourceSets.main.allJava
    include 'cn/howxu/mmcr/api/publicapi/**'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            artifact tasks.named('apiJar')
        }
    }
    repositories {
        maven {
            url "https://maven.howxu.cn"
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}
