runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'info'
        workingDirectory project.layout.projectDirectory.dir('run').dir(name)
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        arguments.addAll('--username', "howxu")
        dependencies {
            // spark
            runtime("curse.maven:${spark_id}:${spark_version}")
            // sodium
            runtime("curse.maven:${sodium_id}:${sodium_version}")
            // athena for ctm
            // runtime("curse.maven:${athena_id}:${athena_version}")
            // lithium
            runtime("maven.modrinth:${lithium_id}:${lithium_version}")
            // time in a bottle
            runtime("maven.modrinth:${tiab_id}:${tiab_version}")
            // modern ui
            // runtime("maven.modrinth:${mui_id}:${mui_version}")
            // JECharacters
            runtime("curse.maven:${jec_id}:${jec_version}")
            // CustomSkinLoader
            runtime("curse.maven:${csl_id}:${csl_version}")
        }
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        modSource project.sourceSets.gametest
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}
