configurations {
    clientMods {
        canBeConsumed = false
        canBeResolved = true
    }
}

dependencies {
    // spark
    clientMods("curse.maven:${spark_id}:${spark_version}")
    // sodium
    clientMods("curse.maven:${sodium_id}:${sodium_version}")
    // athena for ctm
    // clientMods("curse.maven:${athena_id}:${athena_version}")
    // lithium
    clientMods("maven.modrinth:${lithium_id}:${lithium_version}")
    // time in a bottle
    clientMods("maven.modrinth:${tiab_id}:${tiab_version}")
    // modern ui
    // clientMods("maven.modrinth:${mui_id}:${mui_version}")
    // JECharacters
    clientMods("curse.maven:${jec_id}:${jec_version}")
    // AE2 x JEI integration
    clientMods("curse.maven:${ae2xjei_id}:${ae2xjei_version}")
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'info'
        workingDirectory project.layout.projectDirectory.dir('run').dir(name)
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        arguments.addAll('--username', "howxu")
        runtimeClasspath.from(project.configurations.clientMods)
        
        dependencies{
            // CustomSkinLoader
            // 题外话 我真的是有点讨厌cross platform的mod
            // runtime("curse.maven:${csl_id}:${csl_version}")
        }
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        modSource project.sourceSets.gametest
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        arguments.addAll '--existing-mod', 'botania'
    }
}
