plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    alias libs.plugins.modDevGradle
}

version = mod_version
group = mod_group_id

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

base {
    archivesName = mod_id + "-neoforge"
}

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

sourceSets {
    gametest {
        java.srcDirs = ['src/gametest/java']
        resources.srcDirs = ['src/gametest/resources']
        compileClasspath += sourceSets.main.output
        runtimeClasspath += output + sourceSets.main.output
    }
}

sourceSets.test {
    resources.srcDirs('src/test/resources')
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
    testCompileOnly.extendsFrom compileOnly
    testRuntimeOnly.extendsFrom compileOnly
    gametestImplementation.extendsFrom implementation, api
    gametestCompileOnly.extendsFrom compileOnly
    gametestRuntimeOnly.extendsFrom runtimeOnly, localRuntime
}

apply from: "$rootDir/gradle/scripts/repositories.gradle"
apply from: "$rootDir/gradle/scripts/moddevgradle.gradle"
apply from: "$rootDir/gradle/scripts/jars.gradle"
apply from: "$rootDir/gradle/scripts/resources.gradle"
apply from: "$rootDir/gradle/scripts/publishing.gradle"
apply from: "$rootDir/dependencies.gradle"

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    maxParallelForks = 1
    forkEvery = 0
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}