plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.38'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

repositories {
    maven {
        // JEI repo
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        // Modrinth for Rhino
        url = "https://api.modrinth.com/maven" 
    }

    maven {
        // KubeJS
        url = "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }

    maven {
        // Curse Maven
        url "https://cursemaven.com"
    }

    maven {
        // JitPack
        url = 'https://www.jitpack.io'
    }
}

base {
    archivesName = mod_id + "-neoforge"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        workingDirectory project.layout.projectDirectory.dir('run').dir(name)
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    clientData {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    // JEI API
    api("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    // JEI RUNTIME
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // Jade mc26.1 26.1.3
    implementation "curse.maven:jade-324717:8251883"

    // KubeJS 8.0.1
    // implementation("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    compileOnly "curse.maven:kubejs-238086:8219059"
    // interfaceInjectionData("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    // runtimeOnly("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")

    // 2101.2.7-build.85+Rhino-1.21
    implementation "curse.maven:rhino-416294:8218748"
    // Unit testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.25.0'
}

sourceSets.test {
    resources.srcDirs('src/test/resources')
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    maxParallelForks = 1
    forkEvery = 0
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "https://maven.howxu.cn"
            credentials {
                username = System.getenv("MAVEN_USERNAME")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
