dependencies {
    // JEI
    api(forge.jei.api)
    runtimeOnly(forge.jei.impl)

    // Jade mc26.1
    implementation(forge.jade)

    // KubeJS
    implementation(forge.kubejs)

    // Rhino
    implementation(forge.rhino)

    //
    runtimeOnly(forge.athena)
    runtimeOnly(forge.geckolib)
    runtimeOnly(forge.oritech)

    // JUnit
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.25.0'

    // gametest
    gametestCompileOnly fileTree("${gradle.gradleUserHomeDir}/caches/neoformruntime/intermediate_results") {
        include 'compiledWithNeoForge_*_output.jar'
    }
}