org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.238
java_version=21

## Mod Properties
mod_id=mmcr
mod_name=Modular Machinery CR
mod_license=GPL-3.0
# just a keeping filed
mod_version=0.0.0
mod_group_id=cn.howxu

# dependences
jei_version=19.57.0.446
kubejs_version=2101.7.2-build.351
rhino_version=2101.2.7-build.81
jade_version=15.10.1+neoforge
ae2_version=19.2.15
guideme_version=21.1.1
mekanism_version=1.21.1-10.7.18.84

# eae 1.21-2.2.26-neoforge
eae_version=PXAdwHro
# glodium 1.21-2.2-neoforge
glodium_version=pfbmdJ3b
# aeflux 1.21-2.1.1-neoforge
aeflux_version=6465706
# spark 1.10.124 (NeoForge 1.21.1)
spark_version=6225208
# sodium 0.8.13 for NeoForge 1.21.1
sodium_version=8756580
# fusion_version=AFsho5bx
# Athena 4.0.2
athena_version=6669522
# lithium mc1.21.1-0.15.4-neoforge
lithium_version=DDUrRVCA
# Time in a bottle 6.5.4
tiab_version=rG10hU1G
# modern ui 3.13.0.1
mui_version=eMf1VSQd
# jec
jec_version=8381532
# csl
csl_version=8291183

# project id
eae_id=JiOqfoFM
glodium_id=UhW5uCKw
aeflux_id=applied-flux-965012
spark_id=spark-361579
sodium_id=sodium-394468
fusion_id=p19vrgc2
athena_id=athena-841890
lithium_id=gvQqBUqZ
tiab_id=LQdpBqdS
mui_id=3sjzyvGR
jec_id=just-enough-characters-250702
csl_id=customskinloader-286924

# 1.21.1 only deps
ae2wtlib_id=ae2wtlib
ae2wtlib_version=19.3.0
