org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.84

## Mod Properties
mod_id=mmcr
mod_name=Modular Machinery Community Refoxed
mod_license=GPL-3.0
# just a keeping filed
mod_version=0.0.0
mod_group_id=cn.howxu

# dependences
jei_version=29.21.0.65
kubejs_version=26.1.2-8.0.4
mekanism_version=