org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.84
java_version=25

## Mod Properties
mod_id=mmcr
mod_name=Modular Machinery CR
mod_license=GPL-3.0
# just a keeping filed
mod_version=0.0.0
mod_group_id=cn.howxu

# dependences
jei_version=29.21.0.65
kubejs_version=26.1.2-8.0.6
rhino_version=2101.2.8-build.91
jade_version=26.1.3+neoforge
ae2_version=26.1.10-beta
guideme_version=26.1.10-alpha
mekanism_version=26.1.2-10.8.0.homebaked
# Patchouli 26.1-94-beta
patchouli_version=2CsnFLom

# eae 26.1-1.0.3-neoforge
eae_version=KpNzac5y
# glodium 26.1-1.2-neoforge
glodium_version=t0p0CUPy
# aeflux 26.1-1.0.1-neoforge
aeflux_version=8512902
# spark 1.10.187 (NeoForge 26.x)
spark_version=8918574
# sodium 0.9.2
sodium_version=8859590
# fusion_version=AFsho5bx
# athena 4.7.3
athena_version=7970442
# lithium mc26.1.2-0.24.7-neoforge
lithium_version=eZ0KJiEA
# Time in a bottle 8.0.0 for 26.1.2 and above
tiab_version=Wn3zRftS
# modern ui 3.13.0.5
mui_version=pDpDBt4H
# jec
jec_version=8413185
# csl
csl_version=8291183

# project id
eae_id=JiOqfoFM
glodium_id=UhW5uCKw
aeflux_id=applied-flux-965012
spark_id=spark-361579
sodium_id=sodium-394468
# fusion_id=p19vrgc2
athena_id=athena-841890
lithium_id=gvQqBUqZ
tiab_id=LQdpBqdS
mui_id=3sjzyvGR
jec_id=just-enough-characters-250702
csl_id=customskinloader-286924
patchouli_id=nU0bVIaL