license="${mod_license}"
issueTrackerURL="https://github.com/Nibelungorum/ModularMachinery-Community-Refoxed/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="mmcr.png"
authors="howxu"
credits="Based on HellFirePvP code, wiiv most the textures :3, KasumiNova improvements, more MMCE contributors and MMCR contributors!"
description='''
Modular Machinery Community Edition on newer Minecraft! Enjoy brand-new features and extreme performance improvements — unleash your creativity to build multiblock machines and all kinds of recipes!
'''

[[mixins]]
config="mmcr.mixins.json"

[[mixins]]
config="mmcr.jei.mixins.json"
requiredMods=["jei"]

[[mixins]]
config="mmcr.kubejs.mixins.json"
requiredMods=["kubejs"]

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[29.21.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
type="optional"
versionRange="[26.1.2-8.0.4,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"
