modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Nibelungorum/ModularMachinery-Community-Refoxed/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="mmcr.png"
authors="howxu"
credits="Based on HellFirePvP code, wiiv most the textures :3, KasumiNova improvements, more MMCE contributors!"
description='''
Modular Machinery Community Edition on newer Minecraft! Enjoy brand-new features and extreme performance improvements!

Special thanks:
- CZHMC: Textures and UI !
- shifen0520: Textures and UI !
'''

[[mixins]]
config="mixins/extras/mmcr.jei.mixins.json"
requiredMods=["jei"]

[[mixins]]
config="mixins/extras/mmcr.kubejs.mixins.json"
requiredMods=["kubejs"]

[[mixins]]
config="mixins/extras/mmcr.ae2.mixins.json"
requiredMods=["ae2"]

[[mixins]]
config="mixins/extras/mmcr.extendedae_plus.mixins.json"
requiredMods=["ae2", "extendedae", "extendedae_plus"]

[[mixins]]
config="mixins/extras/mmcr.appmek.mixins.json"
requiredMods=["ae2", "mekanism", "appmek"]

[[mixins]]
config="mixins/extras/mmcr.fluxnetworks.mixins.json"
requiredMods=["fluxnetworks"]

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="[19.2.15,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="appflux"
type="optional"
versionRange="[1.21-2.1.1-neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extendedae"
type="optional"
versionRange="[1.21-2.2.26-neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extendedae_plus"
type="optional"
versionRange="[1.6.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
type="optional"
versionRange="[10.7.18,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="athena"
type="optional"
versionRange="[4.0.2,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="appmek"
type="optional"
versionRange="[1.6.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ars_nouveau"
type="optional"
versionRange="[5.11.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="botania"
type="optional"
versionRange="[456-SNAPSHOT,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
versionRange="[6.0.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="fluxnetworks"
type="optional"
versionRange="[8.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="pneumaticcraft"
type="optional"
versionRange="[8.2.21,)"
ordering="AFTER"
side="BOTH"
