license="${mod_license}"
issueTrackerURL="https://github.com/Nibelungorum/ModularMachinery-Community-Refoxed/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="mmcr.png"
authors="howxu"
credits="Based on HellFirePvP code, wiiv most the textures :3, KasumiNova improvements, more MMCE contributors!"
description='''
Modular Machinery Community Edition on newer Minecraft! Enjoy brand-new features and extreme performance improvements!

Special thanks:
- CZHMC: Textures and UI !
- shifen0520: Textures and UI !
'''

[[mixins]]
config="mixins/mmcr.mixins.json"

[[mixins]]
config="mixins/extras/mmcr.jei.mixins.json"
requiredMods=["jei"]

[[mixins]]
config="mixins/extras/mmcr.kubejs.mixins.json"
requiredMods=["kubejs"]

[[mixins]]
config="mixins/extras/mmcr.ae2.mixins.json"
requiredMods=["ae2"]

[[mixins]]
config="mixins/extras/mmcr.extendedae.mixins.json"
requiredMods=["extendedae"]

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.51.0.418,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
type="optional"
versionRange="[2101.7.2-build.351,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.10.1+neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="[19.2.12,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="appflux"
type="optional"
versionRange="[1.21-2.1.1-neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extendedae"
type="optional"
versionRange="[1.21-2.2.26-neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mekanism"
type="optional"
versionRange="[10.7.18.84,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="athena"
type="optional"
versionRange="[4.0.2,)"
ordering="AFTER"
side="BOTH"
