[versions]
jei = "29.21.0.65"
jade = "8251883"
kubejs = "26.1.2-8.0.4-mmcr"
athena = "7970442"
geckolib = "8327201"
oritech = "8571095"
rhino = "8218748"

[libraries]
jei-api = { module = "mezz.jei:jei-26.1.2-neoforge-api", version.ref = "jei" }
jei-impl = { module = "mezz.jei:jei-26.1.2-neoforge", version.ref = "jei" }
jade = { module = "curse.maven:jade-324717", version.ref = "jade" }
kubejs = { module = "dev.latvian.mods:kubejs-neoforge", version.ref = "kubejs" }
rhino = { module = "curse.maven:rhino-416294", version.ref = "rhino" }
athena = { module = "curse.maven:athena-841890", version.ref = "athena" }
geckolib = { module = "curse.maven:geckolib-388172", version.ref = "geckolib" }
oritech = { module = "curse.maven:oritech-1030830", version.ref = "oritech" }