MMCREvents.server(event => {
    const api = event.getAPI()
    event.createStructure('mmcr_example:mana_machine')
        .pattern('IMO', 'PCQ')
        .set('I', api.block('mmcr:item_input_bus'))
        .set('O', api.block('mmcr:item_output_bus'))
        .set('M', api.block('mmcr:basic_casing'))
        .set('P', api.block('mmcr:botania_mana_input_pool'))
        .set('Q', api.block('mmcr:botania_mana_output_pool'))
        .controller('C')
        .build()
    // MMCREvents.server runs inside the active MMCR reload transaction.
    const RecipeBuilder = Java.loadClass('cn.howxu.mmcr.compat.kubejs.MachineRecipeBuilderJS')
    new RecipeBuilder('mmcr_example:mana_recycling')
        .recipePool('mmcr_example:mana_machine')
        .tickTime(100)
        .itemInput('minecraft:iron_ingot', 1)
        .itemOutput('minecraft:gold_ingot', 1)
        .inputMana(25000).outputMana(10000)
        .build()
})
