MMCREvents.server(event => {
    const api = event.getAPI()
    const structure = event.createStructure("mmcr_kubejs:gateway")
        .pattern("   ABA   ", "  D   D  ", "  E   E  ", "  E   E  ", "   FBF   ")
        .pattern("    X    ", "         ", "         ", "         ", "         ")
        .pattern("  GHXHG  ", "I J X J E", "E       E", "E       E", "         ")
        .pattern("A H X H A", "    X    ", "         ", "         ", "F       F")
        .pattern("BXXXXXXXB", "  XX XX  ", "         ", "         ", "B       B")
        .pattern("A H X H A", "    X    ", "         ", "         ", "F       F")
        .pattern("  GHXHG  ", "I J X J I", "E       E", "E       E", "         ")
        .pattern("    X    ", "         ", "         ", "         ", "         ")
        .pattern("   ABA   ", "  D B D  ", "  E C E  ", "  E   E  ", "   FBF   ")
        .set('X', api.anyOf(
            api.block('botania:mana_diamond_block'),
            api.ports()
        ))
        .set('A', api.block('botania:terrasteel_block'))
        .set('B', api.state('botania:elven_gateway_core[state=off]'))
        .set('D', api.state('botania:glimmering_livingwood[axis=x]'))
        .set('E', api.state('botania:glimmering_livingwood[axis=y]'))
        .set('F', api.block('botania:manasteel_block'))
        .set('G', api.block('botania:elementium_block'))
        .set('H', api.state('botania:gaia_pylon[waterlogged=false]'))
        .set('I', api.state('botania:glimmering_livingwood[axis=z]'))
        .set('J', api.state('botania:natura_pylon[waterlogged=false]'))
        .controller('C')
        .build()
})
