MMCREvents.server(event => {
    const api = event.getAPI()
    const structure = event.createStructure("mmcr_kubejs:larger")
        .pattern("XXXXX", "XXXXX", "XXXXX", "ABBBD")
        .pattern("XXXXX", "X   X", "XXXXX", "E F G")
        .pattern("XXXXX", "X   X", "XXXXX", "EH IG")
        .pattern("XXXXX", "X   X", "XXXXX", "E J G")
        .pattern("XXXXX", "XXCXX", "XXXXX", "KLLLM")
        .set('X', api.anyOf(
            api.state('pneumaticcraft:pressure_chamber_wall[wall_state=none]'),
            api.ports()
        ))
        .set('A', api.state('minecraft:stone_stairs[facing=south,half=bottom,shape=outer_left,waterlogged=false]'))
        .set('B', api.state('minecraft:stone_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]'))
        .set('D', api.state('minecraft:stone_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]'))
        .set('E', api.state('minecraft:stone_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]'))
        .set('F', api.state('minecraft:stone_stairs[facing=north,half=top,shape=straight,waterlogged=false]'))
        .set('G', api.state('minecraft:stone_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]'))
        .set('H', api.state('minecraft:stone_stairs[facing=west,half=top,shape=straight,waterlogged=false]'))
        .set('I', api.state('minecraft:stone_stairs[facing=east,half=top,shape=straight,waterlogged=false]'))
        .set('J', api.state('minecraft:stone_stairs[facing=south,half=top,shape=straight,waterlogged=false]'))
        .set('K', api.state('minecraft:stone_stairs[facing=north,half=bottom,shape=outer_right,waterlogged=false]'))
        .set('L', api.state('minecraft:stone_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]'))
        .set('M', api.state('minecraft:stone_stairs[facing=north,half=bottom,shape=outer_left,waterlogged=false]'))
        .controller('C')
        .build()
})
