MMCREvents.server(event => {
    const api = event.getAPI()
    const structure = event.createStructure("mmcr_kubejs:magic")
        .pattern("  ABD  ", "       ", "       ", "       ", "       ", "   E   ", "       ", "       ")
        .pattern(" FGHID ", "       ", "       ", "       ", "       ", "  JKJ  ", "   L   ", "       ")
        .pattern("FMNOPQR", "  NXP  ", "  NXP  ", "  NXP  ", "  STU  ", " VWVWJ ", "  JYJ  ", "   E   ")
        .pattern("ZOHaHOb", "  X X  ", "  X X  ", "  XaX  ", "  W W  ", "LYJ VKE", " EK YL ", "  L E  ")
        .pattern("cdPONef", "  PCN  ", "  PXN  ", "  PXN  ", "  UTS  ", " VTJTJ ", "  VKV  ", "   L   ")
        .pattern(" cdHef ", "       ", "       ", "       ", "       ", "  VYV  ", "   E   ", "       ")
        .pattern("  ghf  ", "       ", "       ", "       ", "       ", "   L   ", "       ", "       ")
        .set('X', api.anyOf(
            api.block('ars_nouveau:sourcestone'),
            api.ports()
        ))
        .set('A', api.state('ars_nouveau:archwood_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]'))
        .set('B', api.state('ars_nouveau:archwood_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]'))
        .set('D', api.state('ars_nouveau:archwood_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]'))
        .set('E', api.state('ars_nouveau:purple_archwood_leaves[distance=5,persistent=true,waterlogged=false]'))
        .set('F', api.state('ars_nouveau:archwood_stairs[facing=south,half=bottom,shape=outer_left,waterlogged=false]'))
        .set('G', api.state('ars_nouveau:archwood_stairs[facing=south,half=bottom,shape=inner_left,waterlogged=false]'))
        .set('H', api.state('ars_nouveau:blue_archwood_wood[axis=y]'))
        .set('I', api.state('ars_nouveau:archwood_stairs[facing=south,half=bottom,shape=inner_right,waterlogged=false]'))
        .set('J', api.state('ars_nouveau:green_archwood_leaves[distance=3,persistent=true,waterlogged=false]'))
        .set('K', api.state('ars_nouveau:purple_archwood_leaves[distance=4,persistent=true,waterlogged=false]'))
        .set('L', api.state('ars_nouveau:green_archwood_leaves[distance=5,persistent=true,waterlogged=false]'))
        .set('M', api.state('ars_nouveau:archwood_stairs[facing=east,half=bottom,shape=inner_right,waterlogged=false]'))
        .set('N', api.state('ars_nouveau:red_archwood_log[axis=y]'))
        .set('O', api.state('ars_nouveau:red_archwood_wood[axis=y]'))
        .set('P', api.state('ars_nouveau:blue_archwood_log[axis=y]'))
        .set('Q', api.state('ars_nouveau:archwood_stairs[facing=west,half=bottom,shape=inner_left,waterlogged=false]'))
        .set('R', api.state('ars_nouveau:archwood_stairs[facing=south,half=bottom,shape=outer_right,waterlogged=false]'))
        .set('S', api.state('ars_nouveau:green_archwood_leaves[distance=1,persistent=true,waterlogged=false]'))
        .set('T', api.state('ars_nouveau:green_archwood_leaves[distance=2,persistent=true,waterlogged=false]'))
        .set('U', api.state('ars_nouveau:purple_archwood_leaves[distance=1,persistent=true,waterlogged=false]'))
        .set('V', api.state('ars_nouveau:purple_archwood_leaves[distance=3,persistent=true,waterlogged=false]'))
        .set('W', api.state('ars_nouveau:purple_archwood_leaves[distance=2,persistent=true,waterlogged=false]'))
        .set('Y', api.state('ars_nouveau:green_archwood_leaves[distance=4,persistent=true,waterlogged=false]'))
        .set('Z', api.state('ars_nouveau:archwood_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]'))
        .set('a', api.state('ars_nouveau:source_lamp[light_level=15,lit=false,powered=false]'))
        .set('b', api.state('ars_nouveau:archwood_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]'))
        .set('c', api.state('ars_nouveau:archwood_stairs[facing=north,half=bottom,shape=outer_right,waterlogged=false]'))
        .set('d', api.state('ars_nouveau:archwood_stairs[facing=east,half=bottom,shape=inner_left,waterlogged=false]'))
        .set('e', api.state('ars_nouveau:archwood_stairs[facing=west,half=bottom,shape=inner_right,waterlogged=false]'))
        .set('f', api.state('ars_nouveau:archwood_stairs[facing=north,half=bottom,shape=outer_left,waterlogged=false]'))
        .set('g', api.state('ars_nouveau:archwood_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]'))
        .set('h', api.state('ars_nouveau:archwood_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]'))
        .controller('C')
        .build()
})
